[package]
name = "gpu_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
log = "0.4.28"
wgpu = "26.0.1"
winit = {version = "0.30.12", optional = true}

[dev-dependencies]
pollster = "0.4.0"

[features]
default=["window"]
window=["dep:winit"]